### ISSUE TITLE
Pawns equip, drop and forbid vanilla EMP or smoke weapons

### ISSUE THREAD

**Issue by uzver91** [emipa606/FindAGunDamnIt#1] opened 2022-04-27 20:48 UTC
Greetings.
My pawns don't want to carry an EMP-grenades or the same type of launchers, they equip and drop it immediately. Outfit policy allow only EMP (both or either), no hunters/brawlers, no modified weapons or other weapon loadout mods in game. It happens no matter what mod setting I use. The same story with smoke weapons. 
I searched in code, but I can't find a propper solution, could you please help me out?

It seems like the mod restrict equiping null-damage weapon (bool compareGuns) or compares range weapons with fists (public static Thing bestGunForPawn). Im not sure, changing some rules didn't help.

**Comment by emipa606** [comment] 2022-04-28 18:47
The issue should be fixed in d737751
It was the vanilla jobdriver that unequipped the weapon so I added an override for it. 
Seems to work as intended now, thanks for the report!

**Closed as completed by emipa606** 2022-04-28 18:47 UTC

**Comment by uzver91** [comment] 2022-04-28 19:03
Good news for me! Now it's all fine, many thanks!
